<?php

namespace AppBundle\Entity;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActive($limit, $page = 1, $section = null, $tag = null)
    {
        $qb = $this->createQueryBuilder('p');

        $qb->where('p.status = :status')
            ->orderBy('p.pubDate', 'DESC')
            ->setMaxResults($limit);

        $qb->setParameter('status', Post::STATUS_PUBLISHED);

        if ($section instanceof Section) {
            $qb->andWhere('p.section = :section');
            $qb->setParameter('section', $section);
        }

        if ($tag) {
            $qb->innerJoin('p.tags', 't', 'WITH', 't.id = :tag')
                ->setParameter('tag', $tag);
        }

        return $qb->getQuery()->execute();
    }
}
