<?php

namespace AppBundle\Entity;
use Doctrine\Common\Collections\Criteria;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActive($limit, $page)
    {
        $criteria = new Criteria();
        $criteria->where($criteria->expr()->eq('status', Post::STATUS_PUBLISHED))
            ->orderBy([
                'pubDate' => 'DESC'
            ])
            ->setMaxResults($limit);

        return $this->matching($criteria);
    }
}
